services:
  mongodb:
    image: mongo:7.0.5
    container_name: product-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db